// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCg39ksyjX64d22Ang2QkL-F-zu3TQ9uo',
    appId: '1:780726668712:web:37046b34d6c7c0992fe19d',
    messagingSenderId: '780726668712',
    projectId: 'teknonews-4e9b3',
    authDomain: 'teknonews-4e9b3.firebaseapp.com',
    storageBucket: 'teknonews-4e9b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uCU0IY_Ts2WaXhe8xWqCbUkRGodZ0Qk',
    appId: '1:780726668712:android:24813a6e527aef002fe19d',
    messagingSenderId: '780726668712',
    projectId: 'teknonews-4e9b3',
    storageBucket: 'teknonews-4e9b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbXoJBICFDF6rWuQCVO_8jI_zu_YSpyEY',
    appId: '1:780726668712:ios:55c2d0c325fc3df22fe19d',
    messagingSenderId: '780726668712',
    projectId: 'teknonews-4e9b3',
    storageBucket: 'teknonews-4e9b3.appspot.com',
    iosBundleId: 'com.example.flutterNewsAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbXoJBICFDF6rWuQCVO_8jI_zu_YSpyEY',
    appId: '1:780726668712:ios:55c2d0c325fc3df22fe19d',
    messagingSenderId: '780726668712',
    projectId: 'teknonews-4e9b3',
    storageBucket: 'teknonews-4e9b3.appspot.com',
    iosBundleId: 'com.example.flutterNewsAppUi',
  );
}
